steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-run-gde-experiments/my-devops-app-gke:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloud-run-gde-experiments/my-devops-app-gke:latest']

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --location=us-central1
      - --cluster=autopilot-cluster-1

images:
  - 'gcr.io/cloud-run-gde-experiments/my-devops-app-gke:latest'

options:
  logging: CLOUD_LOGGING_ONLY
